/* blu-helper data
 *
 * type: "vendor" | "label" | "shelf" | "packaging"
 * region: "US" | "CA" | "UK" | "AUS" | "" (unspecified)
 * parent: name of another entry this one nests under (e.g. partner labels under Vinegar Syndrome)
 * needsReview: true if url/description still needs verification
 */

const COMPANIES = [
  // ---------------- VENDORS ----------------
  { name: "AtomicMovieStore", url: "https://www.atomicmoviestore.com/", type: "vendor", region: "US",
    description: "Specialty storefront stocking import and boutique blu-rays from labels across the blu-ray space." },
  { name: "DiabolikDVD", url: "https://diabolikdvd.com/", type: "vendor", region: "US",
    description: "Long-running boutique vendor carrying releases from nearly every active genre and cult label, domestic and import." },
  { name: "MediaOCD - Discotek", url: "https://www.mediaocd.com/category/discotek", type: "vendor", region: "US",
    description: "Vendor specializing in Discotek Media's anime and tokusatsu catalog plus related imports." },
  { name: "MonsterMaul", url: "https://monstermaul.com/", type: "vendor", region: "US",
    description: "Boutique vendor focused on horror and cult imports that are hard to find elsewhere." },
  { name: "MVDShop", url: "https://mvdshop.com/collections/blu-rays", type: "vendor", region: "US",
    description: "Storefront for MVD Entertainment Group, distributing and selling titles from a wide range of independent labels." },
  { name: "Odyssey Movies", url: "https://odysseymovies.com/", type: "vendor", region: "US",
    description: "Boutique vendor carrying genre, cult, and import blu-ray titles." },
  { name: "OrbitDVD", url: "https://www.orbitdvd.com/", type: "vendor", region: "US",
    description: "Import-focused boutique vendor sourcing region-free and out-of-print genre titles." },
  { name: "RoninFlix", url: "https://roninflix.com/", type: "vendor", region: "US",
    description: "Vendor specializing in Asian cinema imports, particularly Hong Kong and Japanese genre films." },
  { name: "Zavvi", url: "https://us.zavvi.com/", type: "vendor", region: "UK",
    description: "Large retailer known for exclusive steelbooks and limited editions sourced from many labels." },
  { name: "Film Treasures", url: "https://www.filmtreasures.co.uk/", type: "vendor", region: "UK",
    description: "Import and vendor specialist for blu-rays in the UK market." },
  { name: "The Movie Room", url: "https://www.themovieroom.com/", type: "vendor", region: "US",
    description: "Specialty storefront stocking import and boutique blu-rays from labels across the blu-ray space." },
  { name: "Physical Media Vault", url: "https://www.physicalmediavault.com/", type: "vendor", region: "US",
    description: "Specialty storefront stocking import and boutique blu-rays from labels across the blu-ray space." },
  { name: "Blurays For Everyone", url: "https://bluraysforeveryone.com/", type: "vendor", region: "US",
    description: "Specialty storefront stocking import and boutique blu-rays from labels across the blu-ray space." },
  { name: "Terracotta Distro", url: "https://shop.terracottadistribution.com/", type: "vendor", region: "UK",
    description: "UK distributor and label specializing in Asian cinema." },
  { name: "Home Movies Store", url: "https://www.homemovies-store.com/it/", type: "vendor", region: "IT",
    description: "Italian distributor specializing in all things physical media." },
  { name: "Videomatica", url: "https://videomatica.com/", type: "vendor", region: "CA",
    description: "Independent film store and media sales company based in Vancouver, Canada." },
  { name: "Brother Belial", url: "https://brotherbelial.com/", type: "vendor", region: "US",
    description: "Online retailer based in the United States that specializes in boutique physical media, primarily focusing on horror, cult films, and international releases. - credit: lemonade" },
  { name: "Valoria Video", url: "https://valoriavideo.com/", type: "vendor", region: "US",
    description: "Source for rare Blu-ray, 4K UHD, and cult cinema. - credit: lemonade" },

  // ---------------- FILM LABELS ----------------
  { name: "A24", url: "https://shop.a24films.com/collections/blu-rays", type: "label", region: "US",
    description: "Studio/distributor releasing its own theatrical catalog on physical media." },
  { name: "Arbelos Films", url: "https://shoparbelosfilms.com/collections/blu-ray", type: "label", region: "US",
    description: "Boutique label focused on rediscovered and restored arthouse and genre cinema." },
  { name: "Arrow Video", url: "https://www.arrowvideo.com/c/shop/", type: "label", region: "US/CA/UK",
    description: "Genre and cult label known for extensive special editions and restorations." },
  { name: "Toy Robot Video", url: "", type: "label", region: "US", parent: "Arrow Video", needsReview: true,
    description: "Sub-label of Arrow Video." },
  { name: "Cauldron Films", url: "https://www.cauldron-films.com/collections/cauldron-films", type: "label", region: "US",
    description: "Boutique label specializing in obscure horror and exploitation restorations." },
  { name: "Criterion", url: "https://www.criterion.com/", type: "label", region: "US",
    description: "Long-running label known for definitive editions of classic and contemporary art cinema." },
  { name: "Deaf Crocodile", url: "https://deafcrocodile.com/collections/movies", type: "label", region: "US",
    description: "Label restoring and releasing rare international and arthouse genre cinema." },
  { name: "Error 4444", url: "https://error4444.bigcartel.com/", type: "label", region: "US",
    description: "Micro boutique label releasing limited-run horror and underground titles." },
  { name: "Flicker Alley", url: "https://flickeralley.com/", type: "label", region: "US",
    description: "Label specializing in silent film and early cinema restorations." },
  { name: "Full Moon Horror", url: "https://www.fullmoonhorror.com/", type: "label", region: "US",
    description: "Full Moon Features' direct storefront for its own horror and B-movie catalog." },
  { name: "Gold Ninja Video", url: "https://goldninjavideo.com/", type: "label", region: "US",
    description: "Boutique label releasing cult martial arts, action, and exploitation titles." },
  { name: "Kino Lorber", url: "https://kinolorber.com/shop", type: "label", region: "US",
    description: "Distributor and label covering classic, foreign, and independent film catalogs." },
  { name: "Lionsgate Limited", url: "https://lionsgatelimited.com/", type: "label", region: "US",
    description: "Studio storefront for limited and collector editions of Lionsgate's catalog." },
  { name: "Oscilloscope", url: "https://store.oscilloscope.net/", type: "label", region: "US",
    description: "Independent distributor and label releasing select theatrical and festival titles." },
  { name: "RavenBanner", url: "https://ravenbanner.store/", type: "label", region: "US",
    description: "Genre distributor and label focused on independent horror." },
  { name: "SRS Cinema", url: "https://srscinemastore.com/", type: "label", region: "US",
    description: "Micro-budget and underground genre label." },
  { name: "Sentai Filmworks", url: "https://www.sentaifilmworks.com/", type: "label", region: "US",
    description: "Anime distributor and label releasing licensed series and films on physical media." },
  { name: "Severin Films", url: "https://severinfilms.com/", type: "label", region: "US",
    description: "Cult and horror label known for deep-catalog restorations and extras-heavy editions." },
  { name: "Synapse Films", url: "https://www.synapsefilms.com", type: "label", region: "US",
    description: "Long-running genre label specializing in horror and cult restorations." },
  { name: "Terror Vision", url: "https://www.terror-vision.com/", type: "label", region: "US",
    description: "Boutique horror label releasing cult and obscure genre titles." },
  { name: "Troma Direct", url: "https://www.tromadirect.com/", type: "label", region: "US",
    description: "Troma Entertainment's direct storefront for its own catalog of cult films." },
  { name: "Vinegar Syndrome", url: "https://vinegarsyndrome.com/", type: "label", region: "US",
    description: "Major genre label restoring exploitation and horror titles, and host site for several partner labels." },
  { name: "88 Films", url: "https://88-films.myshopify.com/", type: "label", region: "UK",
    description: "UK genre label specializing in martial arts, horror, and cult restorations." },
  { name: "101 Films", url: "https://101-films-store.com/", type: "label", region: "UK",
    description: "UK label releasing genre, cult, and catalog titles." },
  { name: "Chameleon Films", url: "https://shop.chameleonfilms.com.au/collections/our-releases", type: "label", region: "AUS",
    description: "Boutique label releasing genre and cult restorations." },
  { name: "Eureka Video", url: "https://eurekavideo.co.uk/", type: "label", region: "UK",
    description: "UK label known for its Masters of Cinema line of classic and arthouse restorations." },
  { name: "Powerhouse Films - Indicator", url: "https://www.powerhousefilms.co.uk/", type: "label", region: "UK",
    description: "UK label known for densely-extras'd editions across classic Hollywood and cult cinema." },
  { name: "Radiance Films", url: "https://www.radiancefilms.co.uk/", type: "label", region: "UK",
    description: "Label specializing in international cult and arthouse restorations." },
  { name: "Transmission", url: "https://www.radiancefilms.co.uk/collections/transmission", type: "label", region: "", parent: "Radiance Films",
    description: "Sub-label of Radiance Films." },
  { name: "Second Sight Films", url: "https://secondsightfilms.co.uk/", type: "label", region: "UK",
    description: "UK label releasing horror, cult, and genre special editions." },
  { name: "Strange Vice Films", url: "https://www.strangevice.co.uk/films", type: "label", region: "UK",
    description: "Boutique label focused on rare and underground genre titles." },
  { name: "Umbrella Entertainment", url: "https://shop.umbrellaent.com.au/", type: "label", region: "AUS",
    description: "Australian label covering genre, cult, and catalog restorations." },
  { name: "ViaVision - Imprint", url: "https://viavision.com.au/", type: "label", region: "AUS",
    description: "Australian label whose Imprint line releases collector special editions of classic and genre cinema." },
  { name: "Fun City Editions", url: "https://www.funcityeditions.com/shop", type: "label", region: "US",
   description: "Boutique label focused on reissues of maverick repertory cinema and music." },
  { name: "Neon Rated", url: "https://www.neonrated.com/shop/blu-ray", type: "label", region: "US",
   description: "American independent film production and distribution company." },
  { name: "Legends Collection Pictures", url: "https://www.legendscollection.it/", type: "label", region: "IT",
   description: "Italian boutique film label and distributor specializing in the restoration and release of classic Asian and international cinema." },
  { name: "Fondazione Home Movies", url: "https://www.homemovies.it/", type: "label", region: "IT",
   description: "First archive in Italy entirely dedicated to the preservation, restoration, and promotion of private film and audiovisual heritage and amateur cinema." },
  { name: "All the Anime", url: "https://www.alltheanime.com/", type: "label", region: "UK",
   description: "Europe's leading boutique animation distributor. Bringing your favourite anime to cinema, vinyl, and home video." },
  { name: "BFI", url: "https://shop.bfi.org.uk/", type: "label", region: "UK",
   description: "United Kingdom's lead public organization for film and the moving image." },
  { name: "StudioCanal", url: "https://www.studiocanal.com/", type: "label", region: "UK",
   description: "European film and television studio that finances, produces, and distributes hundreds of movies and series globally." },
  { name: "New Wave Video", url: "https://newwavevideo.myshopify.com/collections/all", type: "label", region: "AUS",
   description: "Japanese/ Australian company with the head office in Fujisawa, Japan. Production is shared between both countries." },
  { name: "Hammer FIlms", url: "https://hammerfilms.com/", type: "label", region: "UK",
   description: "Legendary British film production company." },
  { name: "Second Run DVD", url: "https://secondrundvd.ecwid.com/", type: "label", region: "UK",
   description: "UK-based film distribution company dedicated to releasing rare and important classic and contemporary films." },
  { name: "Dark Sky Selects", url: "https://selects.darkskyfilms.com/", type: "label", region: "US",
   description: "Dark Sky Selects is committed to delivering a meticulously curated selection of high-quality, limited edition film releases and exclusive merchandise to the collector's market." },
  { name: "Scorpion Releasing", url: "https://www.orbitdvd.com/collections/scorpion-releasing", type: "label", region: "US",
   description: "Independent home video label that focuses on licensing and restoring cult classics, horror, and independent films." },
  { name: "Unearthed Films", url: "https://www.unearthedfilms.com/store.php", type: "label", region: "US",
   description: "Independent film distribution and production company that imports exploitation films primarily from Eastern Asia." },
  { name: "VCI Entertainment", url: "https://www.vcientertainment.com/", type: "label", region: "US",
   description: "The oldest surviving U.S. independent home video company." },
  { name: "Shameless Screen Entertainment", url: "https://www.shameless-films.com/shop/", type: "label", region: "UK",
   description: "UK-based independent film label renowned for distributing and restoring cult European cinema, particularly Italian horror, giallo, and exploitation films." },
  { name: "Garagehouse Pictures", url: "https://www.orbitdvd.com/collections/garagehouse-pictures", type: "label", region: "US",
   description: "A tiny boutique blu-ray label run by dedicated film collectors and preservationists, who specialize in unique and rare exploitation films in many genres." },
  { name: "Artsploitation Films", url: "https://www.artsploitationfilms.com/", type: "label", region: "US",
   description: "International Films with an Edge." },
  { name: "Grindhouse Releasing", url: "https://shop.grindhousereleasing.com/", type: "label", region: "US",
   description: "Hollywood-based independent cult film distribution." },
  { name: "Gehenna Films", url: "https://gehenna-films.myshopify.com/", type: "label", region: "HU",
   description: "Gehenna Films is an independent film distributor, dedicated to old school horror & cult classic movies on physical media." },
  { name: "Cinema Guild", url: "https://store.cinemaguild.com/homevideo/category/NEW.html", type: "label", region: "US",
   description: "New York-based film distribution company known for acquiring and releasing independent, foreign, and documentary films across North America. - credit: rooommate" },
  { name: "Wicked Vision Media", url: "https://www.wicked-shop.com/en/", type: "label", region: "DE",
   description: "Boutique German film distribution and home entertainment company based in Germany. - credit: inspiration" },
  { name: "Turbine Medien", url: "https://turbine-shop.de/en/", type: "label", region: "DE",
   description: "German boutique media label based in Münster. - credit: inspiration" },
  { name: "Neon Eagle Video", url: "https://www.cauldron-films.com/collections/neon-eagle-video", type: "label", region: "US", parent: "Cauldron Films",
   description: "Boutique video label dedicated to Asian Trash Cinema. - credit: inspiration" },
  { name: "Cauldron Crypt", url: "https://www.cauldron-films.com/collections/cauldron-crypt", type: "label", region: "US", parent: "Cauldron Films",
   description: "Sub-label from Cauldron Films offering deeper cuts into obscure cinema." },
  { name: "Ignite Films", url: "https://www.ignite-films.com/collections/now-available", type: "label", region: "US",
   description: "Specialize in preserving and upgrading classic and cult genre films." },
  { name: "Massacre Video", url: "https://massacrevideo.com/site/?product_cat=blu-ray", type: "label", region: "US",
   description: "Horror, action, exploitation, or documentaries—if it pushes boundaries or breaks rules, it belongs here. - credit: inspiration" },
  { name: "Magnet Releasing", url: "https://www.magnetreleasingfilms.com/", type: "label", region: "US",
   description: "Focus on distributing horror, action, thrillers, international features, and dark comedies. - credit: inspiration" },
  { name: "Rhino Entertainment", url: "https://store.rhino.com/collections/blu-ray-dvd", type: "label", region: "US",
   description: "Holds an exceptional, gold-standard reputation for audiophile-grade Blu-ray Audio releases. - credit: inspiration" },
  { name: "Bayview Entertainment", url: "https://www.bayviewentertainment.com/", type: "label", region: "US",
   description: "American independent media company, film production, and distribution studio based in Pompton Plains, New Jersey. - credit: inspiration" },


  // ---------------- VINEGAR SYNDROME PARTNER LABELS ----------------
  // Sell their catalog through vinegarsyndrome.com rather than running a separate storefront.
  { name: "1-2 Special", url: "https://vinegarsyndrome.com/collections/1-2-special", type: "label", region: "", parent: "Vinegar Syndrome", description: "Partner label releasing through Vinegar Syndrome." },
  { name: "American Genre Film Archive", url: "https://vinegarsyndrome.com/collections/agfa", type: "label", region: "", parent: "Vinegar Syndrome", description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Art Label", url: "https://vinegarsyndrome.com/collections/art-label", type: "label", region: "", parent: "Vinegar Syndrome", description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Big World Pictures", url: "https://vinegarsyndrome.com/collections/big-world-pictures", type: "label", region: "", parent: "Vinegar Syndrome", description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Bizarro", url: "https://vinegarsyndrome.com/collections/bizarro", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Bleeding Skull", url: "https://vinegarsyndrome.com/collections/bleeding-skull", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Brainstorm Media", url: "https://vinegarsyndrome.com/collections/brainstorm-media", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Canadian International Pictures", url: "https://vinegarsyndrome.com/collections/canadian-international-pictures", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Cartuna", url: "https://vinegarsyndrome.com/collections/cartuna", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Cinephobia Releasing", url: "https://vinegarsyndrome.com/collections/cinephobia-releasing", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Circle Collective", url: "https://vinegarsyndrome.com/collections/circle-collective", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Dark Sky", url: "https://vinegarsyndrome.com/collections/dark-sky", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Dark Star", url: "https://vinegarsyndrome.com/collections/dark-star-1", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Delirium Home Video", url: "https://vinegarsyndrome.com/collections/delirium-home-video", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Dekanalog", url: "https://vinegarsyndrome.com/collections/dekanalog", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "ETR Media", url: "https://vinegarsyndrome.com/collections/etr-media", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Factory 25", url: "https://vinegarsyndrome.com/collections/factory-25", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "The Film Desk", url: "https://vinegarsyndrome.com/collections/the-film-desk", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Film Movement", url: "https://vinegarsyndrome.com/collections/film-movement-1", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Film Movement Classics", url: "https://vinegarsyndrome.com/collections/film-movement", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Glass Eye Pix", url: "https://vinegarsyndrome.com/collections/glass-eye-pix", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Gunpowder & Sky", url: "https://vinegarsyndrome.com/collections/gunpowder-sky", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Hope Runs High", url: "https://vinegarsyndrome.com/collections/hope-runs-high", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "The Horror Section", url: "https://vinegarsyndrome.com/collections/the-horror-section", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Icarus Films", url: "https://vinegarsyndrome.com/collections/icarus-films", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "IFC Films", url: "https://vinegarsyndrome.com/collections/ifc-films", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Kani", url: "https://vinegarsyndrome.com/collections/kani", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "KimStim", url: "https://vinegarsyndrome.com/collections/kimstim", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Klubb Super 8", url: "https://vinegarsyndrome.com/collections/klubb-super-8", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Magnolia Pictures", url: "https://vinegarsyndrome.com/collections/magnolia-pictures", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Memory", url: "https://vinegarsyndrome.com/collections/memory", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Muscle", url: "https://vinegarsyndrome.com/collections/muscle", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Music Box Selects", url: "https://vinegarsyndrome.com/collections/music-box-selects", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "NoBudge", url: "https://vinegarsyndrome.com/collections/nobudge", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Pulse Video", url: "https://vinegarsyndrome.com/collections/pulse-video", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Saturn's Core", url: "https://vinegarsyndrome.com/collections/saturns-core", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Seventy-Seven", url: "https://vinegarsyndrome.com/collections/seventy-seven", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Several Futures", url: "https://vinegarsyndrome.com/collections/several-futures", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Shudder", url: "https://vinegarsyndrome.com/collections/shudder", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Subkultur USA", url: "https://vinegarsyndrome.com/collections/subkultur-usa", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Utopia", url: "https://vinegarsyndrome.com/collections/utopia", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "VHSHitfest", url: "https://vinegarsyndrome.com/collections/vhshitfest", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Watermelon Pictures", url: "https://vinegarsyndrome.com/collections/watermelon-pictures", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Wild Eye Releasing", url: "https://vinegarsyndrome.com/collections/wild-eye-releasing", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Willa", url: "https://vinegarsyndrome.com/collections/willa", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "XYZ Films", url: "https://vinegarsyndrome.com/collections/xyz-films", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },
  { name: "Yellow Veil", url: "https://vinegarsyndrome.com/collections/yellow-veil", type: "label", region: "", parent: "Vinegar Syndrome", needsReview: true, description: "Partner label releasing through Vinegar Syndrome." },

  // ---------------- SHELF STAPLES ----------------
  { name: "Alibris", url: "https://www.alibris.com/movies", type: "shelf", region: "US",
    description: "Marketplace for new and used books and movies, useful for hunting out-of-print blu-rays." },
  { name: "DeepDiscount", url: "https://www.deepdiscount.com/movies", type: "shelf", region: "US",
    description: "General discount retailer selling studio catalog blu-rays alongside other media." },
  { name: "GRUV", url: "https://gruv.com/", type: "shelf", region: "US",
    description: "General media retailer selling a broad mix of studio and catalog blu-rays." },
  { name: "GRUV", url: "https://gruv.ca/", type: "shelf", region: "CA",
    description: "Canadian storefront for GRUV's catalog blu-ray selection." },
  { name: "Hamilton Book", url: "https://www.hamiltonbook.com/", type: "shelf", region: "US",
    description: "Discount bookseller that also clears out studio catalog movies and box sets." },
  { name: "MoviesUnlimited", url: "https://www.moviesunlimited.com/", type: "shelf", region: "US",
    description: "Long-running general movie retailer carrying a wide studio catalog selection." },
  { name: "RareWaves", url: "https://www.rarewaves.com/", type: "shelf", region: "UK",
    description: "Long-running general movie retailer carrying a wide studio catalog selection." },
  { name: "MovieZyng", url: "https://moviezyng.com/", type: "shelf", region: "US",
    description: "Dedicated e-commerce destination and distributor for physical media." },
  { name: "Barnes & Noble", url: "https://www.barnesandnoble.com/", type: "shelf", region: "US",
    description: "Largest retail bookseller in the United States, also sells blu-ray. - credit: bowlingwiz300" },
  { name: "WOWHD", url: "https://www.wowhd.co.uk/", type: "shelf", region: "UK",
    description: "International online retailer that specializes in selling physical media, including CDs, vinyl records, 4K UHD discs, and Blu-rays. - credit: Tuudia" },

  // ---------------- PREMIUMS ----------------
  { name: "BluFans", url: "https://bluraysforeveryone.com/collections/steelbooks-metal-blufans", type: "premium", region: "CN",
    description: "Premium limited edition movie releases." },
  { name: "MantaLab", url: "https://www.mantalab.com/collections/all", type: "premium", region: "HK",
    description: "Creates premium SteelBooks and collector editions." },
  { name: "Cinemuseum", url: "https://cinemuseum.myshopify.com/", type: "premium", region: "IT",
    description: "Produces boutique movie collector editions." },
  { name: "Filmarena", url: "https://bluraysforeveryone.com/collections/steelbooks-metal-film-arena", type: "premium", region: "CZ",
    description: "Makes premium SteelBooks and film editions." },
  { name: "HDZeta", url: "https://bluraysforeveryone.com/collections/steelbooks-metal-hdzeta", type: "premium", region: "CN",
    description: "Creates high-end numbered movie releases." },
  { name: "KimchiDVD", url: "https://www.kimchidvd.com/", type: "premium", region: "SK",
    description: "Korean retailer specializing in exclusives." },
  { name: "NovaMedia", url: "https://novamnm.com/category/4k-uhd/143/", type: "premium", region: "SK",
    description: "Releases limited premium movie editions." },
  { name: "Plain Archive", url: "https://www.plainarchive.com/", type: "premium", region: "SK",
    description: "Curates artistic collector film releases." },
];
